name: Studio E2E Tests
on:
  push:
    branches: [master]
    paths:
      - 'packages/pg-meta/**/*'
      - 'apps/studio/**'
      - 'tests/studio-tests/**'
      - 'e2e/studio/**'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [master]
    paths:
      - 'packages/pg-meta/**/*'
      - 'apps/studio/**'
      - 'tests/studio-tests/**'
      - 'e2e/studio/**'
      - 'pnpm-lock.yaml'

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      CI_EMAIL: ${{ secrets.CI_EMAIL }}
      CI_PASSWORD: ${{ secrets.CI_PASSWORD }}
      CI_PROJECT_REF: ${{ secrets.CI_PROJECT_REF }}
      IS_PLATFORM: true

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i

      - name: Build Studio
        run: pnpm --filter studio build

      - name: Start Studio in background
        run: pnpm --filter studio start &
        env:
          PORT: 3000

      - name: Wait for Studio to be ready
        run: |
          timeout=60
          while ! curl -s http://localhost:3000 > /dev/null; do
            sleep 1
            timeout=$((timeout-1))
            if [ $timeout -le 0 ]; then
              echo "Studio failed to start"
              exit 1
            fi
          done

      - name: Install Playwright Browsers
        run: pnpm -C e2e/studio exec playwright install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:3000/dashboard
          IS_PLATFORM: true
        run: pnpm e2e:ci

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-artifacts
          path: |
            e2e/studio/playwright-report/
            e2e/studio/test-results/
          retention-days: 7
