name: Studio E2E Selfhosted

on:
  push:
    branches: [master]
    paths:
      - 'packages/pg-meta/**/*'
      - 'apps/studio/**'
      - 'e2e/studio/**'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [master]
    paths:
      - 'packages/pg-meta/**/*'
      - 'apps/studio/**'
      - 'e2e/studio/**'
      - 'pnpm-lock.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test-selfhosted:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-e2e') }}
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright Browsers
        run: pnpm -C e2e/studio exec playwright install --with-deps

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Get Vercel Preview URL
        id: vercel-url
        uses: patrickedqvist/vercel-preview-url@v1.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_SELFHOSTED }}

      - name: Set ENV Vars for Selfhosted Test
        run: |
          echo "TEST_ENV=preview" >> $GITHUB_ENV
          echo "BASE_URL=${{ steps.vercel-url.outputs.preview-url }}" >> $GITHUB_ENV
          echo "API_BASE_URL=${{ steps.vercel-url.outputs.preview-url }}/api" >> $GITHUB_ENV
          echo "PREVIEW_PROJECT_REF=default" >> $GITHUB_ENV

      - name: Run Playwright selfhosted E2E tests
        run: pnpm -C e2e/studio run e2e:preview

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-selfhosted
          path: e2e/studio/playwright-report/
          retention-days: 7
