name: Studio E2E Tests
on:
  push:
    branches: [master]
    paths:
      - 'packages/pg-meta/**/*'
      - 'apps/studio/**'
      - 'tests/studio-tests/**'
      - 'e2e/studio/**'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [master]
    paths:
      - 'packages/pg-meta/**/*'
      - 'apps/studio/**'
      - 'tests/studio-tests/**'
      - 'e2e/studio/**'
      - 'pnpm-lock.yaml'

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      CI_EMAIL: ${{ secrets.CI_EMAIL }}
      CI_PASSWORD: ${{ secrets.CI_PASSWORD }}
      CI_PROJECT_REF: ${{ secrets.CI_PROJECT_REF }}
      IS_PLATFORM: true

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Cache Next.js build
        uses: actions/cache@v4
        id: nextjs-cache
        with:
          path: |
            apps/studio/.next/cache
          key: ${{ runner.os }}-nextjs-${{ github.event.pull_request.number || github.ref_name }}-${{ hashFiles('apps/studio/**', 'packages/pg-meta/**', 'packages/ai-commands/**', 'packages/common/**', 'packages/config/**', 'packages/icons/**', 'packages/shared-data/**', 'packages/ui/**', 'packages/ui-patterns/**', 'packages/api-types/**', 'pnpm-lock.yaml') }}
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}
      - name: Build Studio
        if: steps.nextjs-cache.outputs.cache-hit != 'true'
        run: pnpm --filter studio build
      - name: Start Studio server
        run: pnpm --filter studio start &
      - name: Wait for Studio server
        run: |
          timeout 60 bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 1; done'
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm -C e2e/studio exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm e2e:ci
        # mark the action as succeeded even if the tests failed. This is temporarily until we make the tests more stable.
        # continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e/studio/playwright-report/
          retention-days: 7
