name: Studio E2E Hosted

on:
  pull_request:
    branches: [master]
    paths:
      - 'apps/studio/**'
      - 'tests/studio-tests/**'
      - 'e2e/studio/**'
      - 'pnpm-lock.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test-hosted:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-e2e') }}
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright Browsers
        run: pnpm -C tests/studio-tests exec playwright install --with-deps

      - name: Wait for Vercel Preview Deployment
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scope: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-args: '--prod=false'

      - name: Run Playwright hosted E2E tests
        run: |
          echo "TEST_ENV=preview" >> $GITHUB_ENV
          echo "BASE_URL=${{ steps.vercel.outputs.preview-url }}" >> $GITHUB_ENV
          echo "API_BASE_URL=https://api.supabase.green" >> $GITHUB_ENV
          echo "PREVIEW_PROJECT_REF=${{ secrets.E2E_PROJECT_REF }}" >> $GITHUB_ENV
      - run: pnpm e2e:preview
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-hosted
          path: tests/studio-tests/playwright-report/
          retention-days: 7
